import { Card, CardColor, CardId, Monument, MonumentId } from './types';

export const CARDS: Record<CardId, Card> = {
  [CardId.COMPOST]: {
    id: CardId.COMPOST,
    name: 'Compost',
    cost: 1,
    color: CardColor.BLUE,
    activations: [1],
    icon: 'Leaf',
    description: 'Recevez 2 pièces de la banque.',
  },
  [CardId.EXTRACTION_CAOUTCHOUC]: {
    id: CardId.EXTRACTION_CAOUTCHOUC,
    name: 'Extraction caoutchouc',
    cost: 1,
    color: CardColor.BLUE,
    activations: [2],
    icon: 'TreePine',
    description: 'Recevez 1 pièce. (Malus RC >= 2°C : 0 pièce). +0.1°C RC.',
    isRC: true,
  },
  [CardId.AMAP]: {
    id: CardId.AMAP,
    name: 'AMAP',
    cost: 2,
    color: CardColor.GREEN,
    activations: [2, 3],
    icon: 'Carrot',
    description: 'Recevez 1 pièce de la banque, uniquement pendant votre tour.',
  },
  [CardId.ATELIER_REPARATION_VELO]: {
    id: CardId.ATELIER_REPARATION_VELO,
    name: 'Atelier de réparation de vélo',
    cost: 2,
    color: CardColor.RED,
    activations: [3],
    icon: 'Wrench',
    description: 'Recevez 2 pièces du joueur qui a lancé les dés.',
  },
  [CardId.MAISON_AUTONOME]: {
    id: CardId.MAISON_AUTONOME,
    name: 'Maison autonome',
    cost: 3,
    color: CardColor.GREEN,
    activations: [4],
    icon: 'Home',
    description: 'Recevez 2 pièces de la banque, uniquement pendant votre tour.',
  },
  [CardId.PUITS_PETROLE]: {
    id: CardId.PUITS_PETROLE,
    name: 'Puits de pétrole',
    cost: 2,
    color: CardColor.BLUE,
    activations: [5],
    icon: 'Droplet',
    description: 'Recevez 2 pièces. (Malus RC >= 2°C : 1 pièce). +0.1°C RC.',
    isRC: true,
  },
  [CardId.CENTRALE_NUCLEAIRE]: {
    id: CardId.CENTRALE_NUCLEAIRE,
    name: 'Centrale nucléaire',
    cost: 8,
    color: CardColor.PURPLE,
    activations: [6],
    icon: 'Zap',
    description: 'Recevez 6 pièces. Si activée 2 fois de suite, votre ville et les cartes 6 de vos voisins sont détruites.',
  },
  [CardId.AEROPORT]: {
    id: CardId.AEROPORT,
    name: 'Aéroport',
    cost: 7,
    color: CardColor.PURPLE,
    activations: [6],
    icon: 'Plane',
    description: 'Chaque joueur vous donne 3 pièces. Si RC >= 2°C, vous payez 5 pièces à la banque.',
  },
  [CardId.BIOCOOP]: {
    id: CardId.BIOCOOP,
    name: 'Biocoop',
    cost: 5,
    color: CardColor.GREEN,
    activations: [7],
    icon: 'ShoppingBag',
    description: 'Recevez 3 pièces par AMAP que vous possédez, uniquement pendant votre tour.',
  },
  [CardId.METHANISATION]: {
    id: CardId.METHANISATION,
    name: 'Unité de méthanisation',
    cost: 4,
    color: CardColor.GREEN,
    activations: [8],
    icon: 'Factory',
    description: 'Recevez 3 pièces par Compost que vous possédez, uniquement pendant votre tour.',
  },
  [CardId.RAFFINERIE]: {
    id: CardId.RAFFINERIE,
    name: 'Raffinerie',
    cost: 5,
    color: CardColor.GREEN,
    activations: [9],
    icon: 'Flame',
    description: 'Recevez 3 pièces par Puits de pétrole. (Malus RC > 3°C : 1 pièce par Puits). +0.1°C RC.',
    isRC: true,
  },
  [CardId.LE_SUN]: {
    id: CardId.LE_SUN,
    name: 'Le Sun',
    cost: 3,
    color: CardColor.RED,
    activations: [9],
    icon: 'Sun',
    description: 'Recevez 3 pièces du joueur qui a lancé les dés.',
  },
  [CardId.EOLIENNE]: {
    id: CardId.EOLIENNE,
    name: 'Éolienne',
    cost: 2,
    color: CardColor.BLUE,
    activations: [9],
    icon: 'Wind',
    description: 'Recevez 3 pièces de la banque.',
  },
  [CardId.USINE_MICHELIN]: {
    id: CardId.USINE_MICHELIN,
    name: 'Usine Michelin',
    cost: 3,
    color: CardColor.GREEN,
    activations: [10],
    icon: 'CircleDashed',
    description: 'Recevez 2 pièces par Extraction caoutchouc. (Malus RC > 3°C : 1 pièce par Extraction). +0.1°C RC.',
    isRC: true,
  },
  [CardId.PANNEAUX_SOLAIRES]: {
    id: CardId.PANNEAUX_SOLAIRES,
    name: 'Panneaux solaires',
    cost: 2,
    color: CardColor.BLUE,
    activations: [11, 12],
    icon: 'SunMedium',
    description: 'Recevez 3 pièces de la banque.',
  },
  [CardId.SIEGE_EELV]: {
    id: CardId.SIEGE_EELV,
    name: 'Siège EELV',
    cost: 10,
    color: CardColor.PURPLE,
    activations: [6],
    icon: 'Shield',
    description: 'Annulation complète et systématique des effets du Réchauffement Climatique pour son propriétaire. (Limité à 1)',
  },
  [CardId.LES_SUBSISTANCES]: {
    id: CardId.LES_SUBSISTANCES,
    name: 'Les subsistances',
    cost: 3,
    color: CardColor.RED,
    activations: [5],
    icon: 'Wheat',
    description: 'Recevez 2 pièces du joueur actif pour chaque carte "Les subsistances" que vous possédez.',
  },
  [CardId.LE_FOYER]: {
    id: CardId.LE_FOYER,
    name: 'Le foyer',
    cost: 3,
    color: CardColor.RED,
    activations: [7],
    icon: 'Home',
    description: 'Recevez 3 pièces du joueur actif pour chaque carte "Le foyer" que vous possédez, sauf si le joueur actif possède lui aussi un Foyer.',
  },
  [CardId.PISTE_SKI_INDOOR]: {
    id: CardId.PISTE_SKI_INDOOR,
    name: 'Piste de ski indoor',
    cost: 5,
    color: CardColor.PURPLE,
    activations: [8],
    icon: 'Snowflake',
    description: 'Recevez 5 pièces de la banque lors de votre tour. (Achat possible uniquement si RC > 2.0°C. Limité à 1)',
  },
  [CardId.PETIT_PAR_SERIN]: {
    id: CardId.PETIT_PAR_SERIN,
    name: 'Petit par serin',
    cost: 3,
    color: CardColor.GREEN,
    activations: [10],
    icon: 'TrendingUp',
    description: 'Recevez 3 pièces de la banque lors de votre tour.',
  },
};

export const MONUMENTS: Record<MonumentId, Monument> = {
  [MonumentId.GARE]: {
    id: MonumentId.GARE,
    name: 'Mont Saint-Michel',
    cost: 5,
    description: 'Vous pouvez lancer 2 dés.',
    icon: 'Castle',
  },
  [MonumentId.CENTRE_COMMERCIAL]: {
    id: MonumentId.CENTRE_COMMERCIAL,
    name: 'Boîte de nuit bolivienne',
    cost: 15,
    description: 'Si vous faites un double, vous rejouez un tour après celui-ci.',
    icon: 'Music',
  },
  [MonumentId.PARC_ATTRACTIONS]: {
    id: MonumentId.PARC_ATTRACTIONS,
    name: "P'tite cafet",
    cost: 30,
    description: 'Une fois par tour, vous pouvez relancer les dés.',
    icon: 'Coffee',
  },
  [MonumentId.TOUR_RADIO]: {
    id: MonumentId.TOUR_RADIO,
    name: 'Domaine de Damian',
    cost: 50,
    description: 'Aucun effet.',
    icon: 'Home',
  },
};

export const INITIAL_SUPPLY: Record<CardId, number> = {
  [CardId.COMPOST]: 6,
  [CardId.EXTRACTION_CAOUTCHOUC]: 6,
  [CardId.AMAP]: 6,
  [CardId.ATELIER_REPARATION_VELO]: 6,
  [CardId.MAISON_AUTONOME]: 6,
  [CardId.PUITS_PETROLE]: 6,
  [CardId.CENTRALE_NUCLEAIRE]: 4,
  [CardId.AEROPORT]: 4,
  [CardId.BIOCOOP]: 6,
  [CardId.METHANISATION]: 6,
  [CardId.RAFFINERIE]: 6,
  [CardId.LE_SUN]: 6,
  [CardId.EOLIENNE]: 6,
  [CardId.USINE_MICHELIN]: 6,
  [CardId.PANNEAUX_SOLAIRES]: 6,
  [CardId.SIEGE_EELV]: 4,
  [CardId.LES_SUBSISTANCES]: 6,
  [CardId.LE_FOYER]: 6,
  [CardId.PISTE_SKI_INDOOR]: 4,
  [CardId.PETIT_PAR_SERIN]: 6,
};
