import { Card, CardColor, CardId, Monument, MonumentId } from './types';

export const CARDS: Record<CardId, Card> = {
  [CardId.CHAMP_DE_BLE]: {
    id: CardId.CHAMP_DE_BLE,
    name: 'Champ de blé',
    cost: 1,
    color: CardColor.BLUE,
    activations: [1],
    icon: 'Wheat',
    description: 'Recevez 1 pièce de la banque, au tour de n\'importe quel joueur.',
  },
  [CardId.FERME]: {
    id: CardId.FERME,
    name: 'Ferme',
    cost: 1,
    color: CardColor.BLUE,
    activations: [2],
    icon: 'Tractor',
    description: 'Recevez 1 pièce de la banque, au tour de n\'importe quel joueur.',
  },
  [CardId.FORET]: {
    id: CardId.FORET,
    name: 'Forêt',
    cost: 3,
    color: CardColor.BLUE,
    activations: [5],
    icon: 'Trees',
    description: 'Recevez 1 pièce de la banque, au tour de n\'importe quel joueur.',
  },
  [CardId.MINE]: {
    id: CardId.MINE,
    name: 'Mine',
    cost: 6,
    color: CardColor.BLUE,
    activations: [9],
    icon: 'Pickaxe',
    description: 'Recevez 5 pièces de la banque, au tour de n\'importe quel joueur.',
  },
  [CardId.VERGER]: {
    id: CardId.VERGER,
    name: 'Verger',
    cost: 3,
    color: CardColor.BLUE,
    activations: [10],
    icon: 'Apple',
    description: 'Recevez 3 pièces de la banque, au tour de n\'importe quel joueur.',
  },
  [CardId.BOULANGERIE]: {
    id: CardId.BOULANGERIE,
    name: 'Boulangerie',
    cost: 1,
    color: CardColor.GREEN,
    activations: [2, 3],
    icon: 'Croissant',
    description: 'Recevez 1 pièce de la banque, uniquement pendant votre tour.',
  },
  [CardId.SUPERETTE]: {
    id: CardId.SUPERETTE,
    name: 'Supérette',
    cost: 2,
    color: CardColor.GREEN,
    activations: [4],
    icon: 'Store',
    description: 'Recevez 3 pièces de la banque, uniquement pendant votre tour.',
  },
  [CardId.FROMAGERIE]: {
    id: CardId.FROMAGERIE,
    name: 'Fromagerie',
    cost: 5,
    color: CardColor.GREEN,
    activations: [7],
    icon: 'Cheese',
    description: 'Recevez 3 pièces de la banque pour chaque établissement "Ferme" que vous possédez, uniquement pendant votre tour.',
  },
  [CardId.FABRIQUE_DE_MEUBLES]: {
    id: CardId.FABRIQUE_DE_MEUBLES,
    name: 'Fabrique de meubles',
    cost: 3,
    color: CardColor.GREEN,
    activations: [8],
    icon: 'Armchair',
    description: 'Recevez 3 pièces de la banque pour chaque établissement "Forêt" et "Mine" que vous possédez, uniquement pendant votre tour.',
  },
  [CardId.MARCHE_FRUITS_LEGUMES]: {
    id: CardId.MARCHE_FRUITS_LEGUMES,
    name: 'Marché fruits & légumes',
    cost: 2,
    color: CardColor.GREEN,
    activations: [11, 12],
    icon: 'Carrot',
    description: 'Recevez 2 pièces de la banque pour chaque établissement "Verger" que vous possédez, uniquement pendant votre tour.',
  },
  [CardId.CAFE]: {
    id: CardId.CAFE,
    name: 'Café',
    cost: 2,
    color: CardColor.RED,
    activations: [3],
    icon: 'Coffee',
    description: 'Recevez 1 pièce du joueur qui a lancé les dés.',
  },
  [CardId.RESTAURANT]: {
    id: CardId.RESTAURANT,
    name: 'Restaurant',
    cost: 3,
    color: CardColor.RED,
    activations: [9, 10],
    icon: 'Utensils',
    description: 'Recevez 2 pièces du joueur qui a lancé les dés.',
  },
  [CardId.STADE]: {
    id: CardId.STADE,
    name: 'Stade',
    cost: 6,
    color: CardColor.PURPLE,
    activations: [6],
    icon: 'Trophy',
    description: 'Recevez 2 pièces de la part de chaque autre joueur, uniquement pendant votre tour.',
  },
  [CardId.CENTRE_AFFAIRES]: {
    id: CardId.CENTRE_AFFAIRES,
    name: 'Centre d\'affaires',
    cost: 8,
    color: CardColor.PURPLE,
    activations: [6],
    icon: 'Briefcase',
    description: 'Échangez un établissement (qui n\'est pas un établissement violet) avec le joueur de votre choix, uniquement pendant votre tour.',
  },
  [CardId.CHAINE_TELEVISION]: {
    id: CardId.CHAINE_TELEVISION,
    name: 'Chaîne de télévision',
    cost: 7,
    color: CardColor.PURPLE,
    activations: [6],
    icon: 'Tv',
    description: 'Recevez 5 pièces du joueur de votre choix, uniquement pendant votre tour.',
  },
};

export const MONUMENTS: Record<MonumentId, Monument> = {
  [MonumentId.GARE]: {
    id: MonumentId.GARE,
    name: 'Gare',
    cost: 4,
    description: 'Vous pouvez lancer 2 dés.',
    icon: 'Train',
  },
  [MonumentId.CENTRE_COMMERCIAL]: {
    id: MonumentId.CENTRE_COMMERCIAL,
    name: 'Centre commercial',
    cost: 10,
    description: 'Vos établissements "Boulangerie" et "Supérette" rapportent 1 pièce de plus.',
    icon: 'ShoppingBag',
  },
  [MonumentId.PARC_ATTRACTIONS]: {
    id: MonumentId.PARC_ATTRACTIONS,
    name: 'Parc d\'attractions',
    cost: 16,
    description: 'Si vous faites un double, vous rejouez un tour après celui-ci.',
    icon: 'FerrisWheel',
  },
  [MonumentId.TOUR_RADIO]: {
    id: MonumentId.TOUR_RADIO,
    name: 'Tour radio',
    cost: 22,
    description: 'Une fois par tour, vous pouvez relancer les dés.',
    icon: 'RadioTower',
  },
};

export const INITIAL_SUPPLY: Record<CardId, number> = {
  [CardId.CHAMP_DE_BLE]: 6,
  [CardId.FERME]: 6,
  [CardId.FORET]: 6,
  [CardId.MINE]: 6,
  [CardId.VERGER]: 6,
  [CardId.BOULANGERIE]: 6,
  [CardId.SUPERETTE]: 6,
  [CardId.FROMAGERIE]: 6,
  [CardId.FABRIQUE_DE_MEUBLES]: 6,
  [CardId.MARCHE_FRUITS_LEGUMES]: 6,
  [CardId.CAFE]: 6,
  [CardId.RESTAURANT]: 6,
  [CardId.STADE]: 4,
  [CardId.CENTRE_AFFAIRES]: 4,
  [CardId.CHAINE_TELEVISION]: 4,
};
